<#
Deploy the AP01 agents-dashboard bridge service to a standalone directory.

The deployed service does NOT depend on this repository:
- Copies service code, fonts, and icons to -TargetDir
- Generates run-bridge.ps1 (hidden-window launcher, idempotent)
- Registers a scheduled task that starts the service at user logon
- Optional -Start launches the service and checks /health

Data source (Codex login state at ~\.codex) is NOT copied; it stays in the
user profile, which is why the task runs as the current user.
#>
param(
    [string]$TargetDir = "$env:LOCALAPPDATA\Cuktech\AP01\agents-dashboard-service",
    [int]$Port = 18765,
    [int]$IntervalSeconds = 300,
    [string]$TaskName = "AP01 Agents Dashboard",
    [string]$Python,
    [switch]$Start
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$packageDir = Join-Path $repoRoot "features\agents_dashboard"
$fontDir = Join-Path $repoRoot "fonts"

# --- resolve python ---
if (-not $Python) {
    $cmd = Get-Command python -ErrorAction SilentlyContinue
    if (-not $cmd) { throw "python not found on PATH; pass -Python <path-to-python.exe>" }
    $Python = $cmd.Source
}
if (-not (Test-Path $Python)) { throw "python not found: $Python" }

# --- check Pillow ---
& $Python -c "import PIL" 2>$null
if ($LASTEXITCODE -ne 0) {
    throw "Pillow is not installed for $Python; run: $Python -m pip install Pillow"
}

# --- port must be free (an old project-based service would collide) ---
$inUse = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($inUse) {
    $owners = ($inUse | Select-Object -ExpandProperty OwningProcess -Unique) -join ", "
    throw "Port $Port is already in use (PID $owners). Stop the existing bridge service first (e.g. the one started from the project directory), then retry."
}

# --- validate source files ---
$required = @(
    (Join-Path $repoRoot "features\__init__.py"),
    (Join-Path $packageDir "bridge.py"),
    (Join-Path $packageDir "renderer.py"),
    (Join-Path $packageDir "assets\icons"),
    $fontDir
)
foreach ($path in $required) {
    if (-not (Test-Path $path)) { throw "missing required source: $path" }
}

# --- prepare target ---
$TargetDir = [System.IO.Path]::GetFullPath($TargetDir)
if (Test-Path (Join-Path $TargetDir "run-bridge.ps1")) {
    throw "target already deployed: $(Join-Path $TargetDir 'run-bridge.ps1'); remove it or choose another directory"
}
New-Item -ItemType Directory -Force -Path (Join-Path $TargetDir "features\agents_dashboard") | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $TargetDir "fonts") | Out-Null

# --- copy package code (exclude tests) ---
Copy-Item (Join-Path $repoRoot "features\__init__.py") `
    (Join-Path $TargetDir "features\__init__.py") -Force
Get-ChildItem (Join-Path $packageDir "*.py") |
    Where-Object { $_.Name -notlike "test_*" } |
    ForEach-Object {
        Copy-Item $_.FullName `
            (Join-Path $TargetDir "features\agents_dashboard\$($_.Name)") -Force
    }
Copy-Item (Join-Path $packageDir "assets") `
    (Join-Path $TargetDir "features\agents_dashboard\assets") -Recurse -Force
Get-ChildItem $fontDir | ForEach-Object {
    Copy-Item $_.FullName (Join-Path $TargetDir "fonts\$($_.Name)") -Force
}

# --- generate hidden-window launcher (idempotent: exits if port is taken) ---
$launcherTemplate = @'
# Auto-generated by deploy-agents-dashboard.ps1. Starts the AP01 agents
# dashboard bridge with a hidden window. Safe to run repeatedly.
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$port = __PORT__

$listening = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
if ($listening) { Write-Host "bridge already running on port $port"; exit 0 }

Start-Process -FilePath "__PYTHON__" `
  -ArgumentList @(
    "-m", "features.agents_dashboard.bridge",
    "--bind", "0.0.0.0",
    "--port", "$port",
    "--interval", "__INTERVAL__",
    "--output", ('"{0}"' -f (Join-Path $root "service-output")),
    "--cache-directory", ('"{0}"' -f (Join-Path $root "service-cache")),
    "--font-directory", ('"{0}"' -f (Join-Path $root "fonts"))
  ) `
  -WorkingDirectory $root -WindowStyle Hidden `
  -RedirectStandardOutput (Join-Path $root "bridge.log") `
  -RedirectStandardError (Join-Path $root "bridge-err.log")
Write-Host "bridge started on port $port"
'@
$launcherContent = $launcherTemplate.
    Replace("__PORT__", [string]$Port).
    Replace("__INTERVAL__", [string]$IntervalSeconds).
    Replace("__PYTHON__", $Python)
$launcher = Join-Path $TargetDir "run-bridge.ps1"
Set-Content -Path $launcher -Value $launcherContent -Encoding UTF8

# --- register scheduled task (start at user logon, auto restart) ---
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false }
$action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$launcher`"" `
    -WorkingDirectory $TargetDir
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0)
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings | Out-Null

Write-Host "Deployed to: $TargetDir"
Write-Host "Scheduled task: $TaskName (starts at user logon)"
Write-Host "Launcher: $launcher"

# --- optional: start now and health-check ---
if ($Start) {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $launcher
    $deadline = (Get-Date).AddSeconds(30)
    $healthy = $false
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Seconds 2
        try {
            $resp = Invoke-WebRequest -Uri "http://127.0.0.1:$Port/health" `
                -UseBasicParsing -TimeoutSec 3
            if ($resp.StatusCode -eq 200) { $healthy = $true; break }
        } catch { }
    }
    if ($healthy) {
        Write-Host "Health check passed: http://127.0.0.1:$Port/health"
    } else {
        throw "service did not become healthy within 30 seconds; check $TargetDir\bridge.log and $TargetDir\bridge-err.log"
    }
}
